---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services"]
  verbs: [ "get", "list", "watch"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pg-role
subjects:
- kind: ServiceAccount
  name: pg-access 
  namespace: {{ .Values.namespace }}
