apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: {{ .Values.namespace }}
  labels:
    applicationid: {{ .Values.application_id }}
    environment: {{ .Values.environment }}
    role: pg
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    applicationid: {{ .Values.application_id }}
    environment: {{ .Values.environment }}
    role: pg
